import Foundation
import Testing
import TsugumiValidationSupport
@testable import Tsugumi

/// PLAN_VISION §5 V1's exit condition: our preprocessing agrees with the
/// reference dump.
///
/// "Agrees" is not "is identical". Our resize is CoreGraphics, upstream's is
/// torchvision bicubic with antialiasing, and the two do not produce the same
/// bytes — nor can they, since upstream's own PIL and torchvision paths disagree
/// with each other (§4-3). What *is* exact is the geometry and the layout: the
/// patch grid, the patch count, the soft-token count, and the order of elements
/// inside a patch are all integer facts, and any of them being wrong is a bug
/// rather than a rounding difference.
///
/// So this suite splits the two: equality for everything integral, and a bound
/// on the pixels that is loose enough to admit a different resampler but tight
/// enough to fail a transpose — with the transpose actually tried, because a
/// tolerance nobody has seen fail is not evidence (§6-3).
@Suite("VisionPreprocessorFixtures")
struct VisionPreprocessorFixtureTests {

    private func fixtures() throws -> [VisionFixtures.Case]? {
        try VisionFixtures.load()
    }

    @Test("Geometry matches the reference dump exactly")
    func geometryMatchesFixtures() throws {
        guard let cases = try fixtures() else {
            // Generated by Scripts/vision/dump_vision_fixtures.py; 195 MB, so
            // they live under scratch/ and this degrades instead of failing.
            return
        }
        #expect(!cases.isEmpty)
        for fixture in cases {
            let config = try VisionPreprocessorConfig(maxSoftTokens: fixture.maxSoftTokens)
            let geometry = try config.geometry(imageWidth: fixture.imageWidth,
                                               imageHeight: fixture.imageHeight)
            #expect(geometry.patchesWide == fixture.patchesWide, "\(fixture.name) grid width")
            #expect(geometry.patchesHigh == fixture.patchesHigh, "\(fixture.name) grid height")
            #expect(geometry.patchCount == fixture.patchCount, "\(fixture.name) patch count")
            #expect(geometry.softTokenCount == fixture.softTokenCount, "\(fixture.name) soft tokens")

            let reference = try fixture.tensor("pixel_values")
            #expect(reference.shape == [fixture.patchCount, 768], "\(fixture.name) reference shape")
        }
    }

    @Test("Patch values track the reference, and a transposed grid does not")
    func pixelValuesTrackReference() throws {
        guard let cases = try fixtures() else { return }
        let imageRoot = URL(fileURLWithPath: VisionFixtures.defaultRoot)
            .appendingPathComponent("images")

        for fixture in cases {
            let imageURL = imageRoot.appendingPathComponent(fixture.imageName)
            guard FileManager.default.fileExists(atPath: imageURL.path) else { continue }

            let config = try VisionPreprocessorConfig(maxSoftTokens: fixture.maxSoftTokens)
            let processed = try VisionImagePreprocessor.preprocess(contentsOf: imageURL, config: config)
            let reference = try fixture.tensor("pixel_values")
            #expect(processed.patches.count == reference.count, "\(fixture.name) element count")
            guard processed.patches.count == reference.count else { continue }

            let ours = processed.patches.map(Float.init)
            let aligned = meanAbsoluteDifference(ours, reference.values)
            let transposed = meanAbsoluteDifference(
                transposePatchGrid(ours, geometry: processed.geometry), reference.values)

            // Values are in [0, 1]. A resampler difference on a photograph-like
            // image lands well under 0.05; the ring pattern in the fixtures is
            // deliberately high-frequency, which is the hard case for this.
            // §6-1 layer C is a *measurement*, not a gate: printing it is how
            // the resize difference gets attributed later, when layer B pins
            // the tower and the end-to-end gap has to be explained.
            print("[vision-preproc] \(fixture.name): mean|diff| aligned=\(aligned) transposed=\(transposed)")
            #expect(aligned < 0.05, "\(fixture.name) mean |diff| = \(aligned)")
            // Detection power: the same measurement on a transposed grid must
            // fail the bound it just passed. Without this the bound proves
            // nothing about whether the layout is right.
            #expect(transposed > aligned * 3,
                    "\(fixture.name) transposed \(transposed) vs aligned \(aligned)")
            #expect(ours.allSatisfy { $0 >= 0 && $0 <= 1 }, "\(fixture.name) range")
        }
    }

    /// Reorder patches as if the grid had been walked column-major. Same
    /// multiset of values, different layout — so it isolates ordering from
    /// resampling.
    private func transposePatchGrid(_ values: [Float], geometry: VisionImageGeometry) -> [Float] {
        let stride = values.count / geometry.patchCount
        var out = [Float](repeating: 0, count: values.count)
        for patch in 0..<geometry.patchCount {
            let (x, y) = geometry.position(ofPatch: patch)
            let swapped = min(x * geometry.patchesHigh + y, geometry.patchCount - 1)
            for i in 0..<stride {
                out[patch * stride + i] = values[swapped * stride + i]
            }
        }
        return out
    }

    private func meanAbsoluteDifference(_ a: [Float], _ b: [Float]) -> Float {
        guard a.count == b.count, !a.isEmpty else { return .infinity }
        var total = Double(0)
        for i in 0..<a.count {
            guard a[i].isFinite, b[i].isFinite else { return .infinity }
            total += Double(abs(a[i] - b[i]))
        }
        return Float(total / Double(a.count))
    }
}
